apiVersion: v1
kind: Namespace
metadata:
  name: cohortapps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cohortapp
  namespace: cohortapps
spec:
  selector:
    matchLabels:
      app: cohortapp
  replicas: 1
  template: 
    metadata:
      labels:
        app: cohortapp
    spec:
      containers:
      - name: cohortapp
        image: ${REPOSITORY_TAG}
        resources:
          requests:
             memory: 100Mi
             cpu: 0.25
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cohortapp-svc
  namespace: cohortapps

spec:
 
  selector:
    app: cohortapp

  ports:
    - name: http
      port: 80
      nodePort: 30000

  type: NodePort
